package com.entity;

/**
 * TBook generated by MyEclipse Persistence Tools
 */

public class TBook implements java.io.Serializable
{

	// Fields

	private Integer id;
	private String name;
	private String zuozhe;
	private String chubanshe;

	private String chubanriqi;
	private String isbm;
	private String price;
	private String yeshu;

	private String kucun;
	private int catelog_id;
	private String del;
	
	
	public int getCatelog_id()
	{
		return catelog_id;
	}
	public void setCatelog_id(int catelog_id)
	{
		this.catelog_id = catelog_id;
	}
	public String getChubanriqi()
	{
		return chubanriqi;
	}
	public void setChubanriqi(String chubanriqi)
	{
		this.chubanriqi = chubanriqi;
	}
	public String getChubanshe()
	{
		return chubanshe;
	}
	public void setChubanshe(String chubanshe)
	{
		this.chubanshe = chubanshe;
	}
	public String getDel()
	{
		return del;
	}
	public void setDel(String del)
	{
		this.del = del;
	}
	public Integer getId()
	{
		return id;
	}
	public void setId(Integer id)
	{
		this.id = id;
	}
	public String getIsbm()
	{
		return isbm;
	}
	public void setIsbm(String isbm)
	{
		this.isbm = isbm;
	}
	public String getKucun()
	{
		return kucun;
	}
	public void setKucun(String kucun)
	{
		this.kucun = kucun;
	}
	public String getName()
	{
		return name;
	}
	public void setName(String name)
	{
		this.name = name;
	}
	public String getPrice()
	{
		return price;
	}
	public void setPrice(String price)
	{
		this.price = price;
	}
	public String getYeshu()
	{
		return yeshu;
	}
	public void setYeshu(String yeshu)
	{
		this.yeshu = yeshu;
	}
	public String getZuozhe()
	{
		return zuozhe;
	}
	public void setZuozhe(String zuozhe)
	{
		this.zuozhe = zuozhe;
	}
	
	
	
}