package com.entity;

/**
 * TJieyue generated by MyEclipse Persistence Tools
 */

public class TJieyue implements java.io.Serializable
{

	private Integer id;
	private int user_id;
	private int book_id;
	private int jieyueshuliang;

	private String jieyueshijian;
	private String shifouguihuan;
	private String guihuanshijian;
	private String del;
	
	
	private TUser user;
	private TBook book;
	
	public int getBook_id()
	{
		return book_id;
	}
	public void setBook_id(int book_id)
	{
		this.book_id = book_id;
	}
	public String getDel()
	{
		return del;
	}
	public void setDel(String del)
	{
		this.del = del;
	}
	public String getGuihuanshijian()
	{
		return guihuanshijian;
	}
	public void setGuihuanshijian(String guihuanshijian)
	{
		this.guihuanshijian = guihuanshijian;
	}
	public Integer getId()
	{
		return id;
	}
	
	public TBook getBook()
	{
		return book;
	}
	public void setBook(TBook book)
	{
		this.book = book;
	}
	public TUser getUser()
	{
		return user;
	}
	public void setUser(TUser user)
	{
		this.user = user;
	}
	public void setId(Integer id)
	{
		this.id = id;
	}
	public String getJieyueshijian()
	{
		return jieyueshijian;
	}
	public void setJieyueshijian(String jieyueshijian)
	{
		this.jieyueshijian = jieyueshijian;
	}
	public String getShifouguihuan()
	{
		return shifouguihuan;
	}
	
	public int getJieyueshuliang()
	{
		return jieyueshuliang;
	}
	public void setJieyueshuliang(int jieyueshuliang)
	{
		this.jieyueshuliang = jieyueshuliang;
	}
	public void setShifouguihuan(String shifouguihuan)
	{
		this.shifouguihuan = shifouguihuan;
	}
	public int getUser_id()
	{
		return user_id;
	}
	public void setUser_id(int user_id)
	{
		this.user_id = user_id;
	}
	
	
}